Change user `bpfctl` to `bpfd-clients`
redhat-et/bpfd pull request #118
Opened 2022-08-30 13:45 UTC by Billy99

This is a continuation from #110.

Change user `bpfctl` to `bpfd-clients` and move `/etc/bpfd/bytecode/` to
`/var/bpfd/bytecode/`.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

2022-08-30 13:53 UTC, Billy99 commented
I can change the name if something is preferred over `bpfd-clients`.

2022-08-30 14:50 UTC, dave-tucker requested changes
I don't think we should do this. See: #117 for context.
We can discuss more on the call today.

2022-08-30 14:53 UTC, astoycos commented
/lgtm

2022-08-30 21:24 UTC, Billy99 commented
> I don't think we should do this. See: #117 for context.

OK, I updated the PR. It no longer changes the name of the user. Now just tweaks the scripts to hopefully be more clear as to how the strings `bpfd` and `bpfctl` are used (are they the User, the User Group or the Binary).

2022-08-31 07:49 UTC, dave-tucker approved these changes
LGTM. Thanks @Billy99

2022-08-31 07:51 UTC, merged